dist: trusty
sudo: false
notifications:
  email: false
env:
  - RELEASE_TAG="release-$TRAVIS_BUILD_NUMBER"
  - CF_API_URL="api.sys.evans.pal.pivotal.io"
  - CF_ORG="ankit.goel.rbs.co.uk"
  - CF_SPACE="sandbox"
  - CF_USERNAME="ankit.goel.rbs.co.uk"
  - CF_PASSWORD="8n6s8syw"
  - GITHUB_USERNAME="anandmishra15"
  - GITHUB_OAUTH_TOKEN="910c665d466beb27250b70ba3eeabd6c12e6a9a0"
if: tag IS blank


jobs:
  include:
    - stage: build and publish
      language: java
      jdk: openjdk11
      install: skip
      script: ./gradlew clean build
      before_deploy:
        - git config --local user.name "Travis CI"
        - git config --local user.email "travis@example.com"
        - git tag -f $RELEASE_TAG
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        file: "build/libs/pal-tracker.jar"
        skip_cleanup: true
    - stage: deploy to cf
      language: bash
      script:
        - echo "Downloading $RELEASE_TAG"
        - wget -P build/libs https://github.com/$GITHUB_USERNAME/pal-tracker/releases/download/$RELEASE_TAG/pal-tracker.jar
      before_deploy:
        - echo "Deploying $RELEASE_TAG to Cloud Foundry"
      deploy:
        provider: cloudfoundry
        api: $CF_API_URL
        username: $CF_USERNAME
        password: $CF_PASSWORD
        organization: $CF_ORG
        space: $CF_SPACE
